name: Target

attributes:
  ORGANIZATIONNAME: nuomi1

targets:
  Target_Example:
    type: application
    platform: iOS
    deploymentTarget: 10.0
    sources:
      - Target
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.cocoapods.demo.Target-Example
        SWIFT_VERSION: 5.0
